name: Build & Deploy GitHub Pages (preview / production)

on:
  # PR を開く・更新 ⇒ プレビュー
  pull_request:
    types: [opened, reopened, synchronize]
  # main へ push ⇒ 本番デプロイ
  push:
    branches: [main]
  # 手動実行
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  # プレビューは PR 番号単位 / 本番は固定グループ
  group: ${{ github.event_name == 'pull_request'
            && format('pages-preview-{0}', github.event.pull_request.number)
            || 'pages-production' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # ---------- ビルド ----------
      - name: Install & Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build          # → frontend/dist に出力

      # ---------- 成果物アップロード ----------
      - uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist    # ★ 修正ポイント
          name: github-pages     # 本番／プレビューどちらでも同じ名前で OK

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Pages 用の環境を指定（存在しなければ自動生成される）
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # PR のときだけ preview=true
          preview: ${{ github.event_name == 'pull_request' }}
          # artifact_name はデフォルトで github-pages

