name: Build Tauri App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: tauri-apps/tauri-action@v0
        env:
          TAURI_ACTION: build
          TAURI_PROJECT_PATH: frontend
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
